SELECT CODICE_AUTORE,NOME,COGNOME,N_LIBRI_SCRITTI
FROM AUTORE AS A, (SELECT CODICE_AUTORE_SCRITTO, COUNT(CODICE_AUTORE_SCRITTO) AS N_LIBRI_SCRITTI
		    FROM SCRITTO  
		    GROUP BY CODICE_AUTORE_SCRITTO 
		    HAVING COUNT(CODICE_AUTORE_SCRITTO)=(SELECT MAX(N) 
							  FROM (SELECT CODICE_AUTORE_SCRITTO, COUNT(CODICE_AUTORE_SCRITTO) AS N 
								FROM SCRITTO
								GROUP BY CODICE_AUTORE_SCRITTO) AS I)) AS N_LIBRI
WHERE A.CODICE_AUTORE=N_LIBRI.CODICE_AUTORE_SCRITTO
