SELECT CODICE_EDITORE,NOME_EDITORE,N_LIBRI_PUBBLICATI
FROM EDITORE AS E, (SELECT CODICE_EDITORE_PUBBLICA, COUNT(CODICE_EDITORE_PUBBLICA) AS N_LIBRI_PUBBLICATI
					FROM PUBBLICA  
					GROUP BY CODICE_EDITORE_PUBBLICA
					HAVING COUNT(CODICE_EDITORE_PUBBLICA)=(
                    			SELECT MAX(N) 
					FROM (SELECT CODICE_EDITORE_PUBBLICA, COUNT(CODICE_EDITORE_PUBBLICA) AS N 
							FROM PUBBLICA
							GROUP BY CODICE_EDITORE_PUBBLICA) AS CASA_EDITRICE)) AS N_LIBRI
WHERE E.CODICE_EDITORE=N_LIBRI.CODICE_EDITORE_PUBBLICA
