SELECT CODICE_LIBRO,TITOLO,ISBN,COD_P
FROM LIBRO AS LI,(SELECT CODICE_LIBRO_CONCESSO, COD_P
FROM (SELECT CODICE_LIBRO_CONCESSO, COUNT(CODICE_PRESTITO_CONCESSO) AS COD_P
	  FROM CONCESSO 
	  GROUP BY CODICE_LIBRO_CONCESSO
	  HAVING COD_P=(SELECT MAX(CPC)
				 FROM(SELECT CODICE_LIBRO_CONCESSO, COUNT(CODICE_PRESTITO_CONCESSO) AS CPC
				 FROM CONCESSO
				 GROUP BY CODICE_LIBRO_CONCESSO
				 ORDER BY CPC DESC)AS MAS_QUERY))AS TAB_COMPLETE) AS L
WHERE LI.CODICE_LIBRO = L.CODICE_LIBRO_CONCESSO
ORDER BY LI.CODICE_LIBRO ASC;
