SELECT NOME_SUCCURSALE_PRESTITO,COD_P
FROM (SELECT NOME_SUCCURSALE_PRESTITO, COUNT(CODICE_PRESTITO) AS COD_P
		FROM PRESTITO
		GROUP BY NOME_SUCCURSALE_PRESTITO
		HAVING COUNT(CODICE_PRESTITO)=(SELECT MAX(CP)
						FROM(SELECT NOME_SUCCURSALE_PRESTITO, COUNT(CODICE_PRESTITO) AS CP
						FROM PRESTITO
                                        	GROUP BY NOME_SUCCURSALE_PRESTITO
                                        	ORDER BY CP DESC)AS MAX)) AS MAX_PRESTITO
ORDER BY NOME_SUCCURSALE_PRESTITO ASC;






