SELECT NOME_SUCCURSALE_PRESENTE_IN,NUMERO_COPIE
FROM PRESENTE_IN AS P, LIBRO AS L
WHERE P.CODICE_LIBRO_PRESENTE_IN=L.CODICE_LIBRO
AND (L.CODICE_LIBRO='' OR L.TITOLO='' OR L.ISBN='')
ORDER BY NOME_SUCCURSALE_PRESENTE_IN ASC;
